### ISSUE TITLE
timestamp.dat  ?

### ISSUE THREAD

**Issue by Hub-er** [tbrouns/eyestalker#2]
hello,but where is the timestamp.dat?

**Comment by tbrouns** [comment]
Hi @Hub-er, 

The offline or "no-cam" version of the program does not save a "timestamp.dat" data file, because there are no timestamps available. This is only relevant if there is a camera that can provide the timestamps, which is not the case when you just process PNG images. If you still want to use timestamps in combination with images, you can just note down the frame-rate that you are using and create a timestamp array based on that frame-rate.
